import express from "express";
import multer from "multer";
import swaggerUi from "swagger-ui-express";
import { swaggerSpec } from "./swagger.js";
import { processPdf } from "./pdf.js";
import { askQuestion } from "./qa.js";
import { initCollection } from "./qdrant.js";

const app = express();
const upload = multer({ dest: "uploads/" });

app.use(express.json());

initCollection();

/**
 * @swagger
 * /upload-pdf:
 *   post:
 *     summary: Upload a PDF and index it into Qdrant
 *     requestBody:
 *       required: true
 *       content:
 *         multipart/form-data:
 *           schema:
 *             type: object
 *             properties:
 *               pdf:
 *                 type: string
 *                 format: binary
 *     responses:
 *       200:
 *         description: PDF processed successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 docId:
 *                   type: string
 */
app.post("/upload-pdf", upload.single("pdf"), async (req, res) => {
  const docId = await processPdf(req.file.path);
  res.json({ docId });
});

/**
 * @swagger
 * /ask:
 *   post:
 *     summary: Ask a question using a previously uploaded PDF
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - docId
 *               - question
 *             properties:
 *               docId:
 *                 type: string
 *               question:
 *                 type: string
 *     responses:
 *       200:
 *         description: Answer generated by llama3.2
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 answer:
 *                   type: string
 */
app.post("/ask", async (req, res) => {
  const { docId, question } = req.body;
  const answer = await askQuestion(docId, question);
  res.json({ answer });
});

app.use("/docs", swaggerUi.serve, swaggerUi.setup(swaggerSpec));

app.listen(3000, () =>
  console.log("Server running on http://localhost:3000\nSwagger → http://localhost:3000/docs")
);
